---
#tasks file for cs2modrewrite
- name: Install unarchive dependencies
  ansible.builtin.package:
    name:
    - unzip
    - tar

- name: Install argparse
  ansible.builtin.pip:
    name: argparse
  register: argparse_output
  changed_when: "'Using cached argparse' not in argparse_output.stdout and 'Requirement already satisfied' not in argparse_output.stdout"

- name: Create the /tools/cs2modrewrite directory
  ansible.builtin.file:
    mode: 0755
    path: /tools/cs2modrewrite
    state: directory

- name: Download and untar the cs2modrewrite tarball
  ansible.builtin.unarchive:
    src: https://github.com/threatexpress/cs2modrewrite/tarball/master
    dest: /tools/cs2modrewrite
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
    creates: /tools/cs2modrewrite/cs2modrewrite.py
