---
- name: Install git
  ansible.builtin.package:
    name: git
    state: present
    update_cache: yes

- name: Install argparse
  ansible.builtin.pip:
    name: argparse
  register: argparse_output
  changed_when: "'Using cached argparse' not in argparse_output.stdout"

- name: Install cs2modrewrite
  ansible.builtin.git:
    repo: "https://github.com/threatexpress/cs2modrewrite.git"
    dest: '{{ playbook_dir }}/tools/cs2modrewrite'
    version: master
